PRAGMA encoding="UTF-8";
DROP TABLE POSITION;
CREATE TABLE POSITION(
ID TEXT Primary key,
AREA TEXT, 
NAME TEXT,
LATITUDE double, 
LONGITUDE double);

INSERT INTO POSITION (ID, AREA, NAME, LATITUDE, LONGITUDE) VALUES ('f', 'd', 'e', 33.4, 55.6);
